name: Build and Publish NPM Package

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm ci

      - name: Build Project
        run: npm run build

      - name: Set Version From Tag
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          npm version $VERSION --no-git-tag-version

      # -----------------------------
      # Publish to GitHub Packages
      # -----------------------------
      - name: Configure GitHub Registry
        run: |
          echo "@surerakeshkumar:registry=https://npm.pkg.github.com" >> .npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> .npmrc

      - name: Publish to GitHub Packages
        run: npm publish --registry=https://npm.pkg.github.com

      # -----------------------------
      # Publish to NPMJS
      # -----------------------------
      - name: Configure NPMJS Registry
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" >> .npmrc

      - name: Publish to NPMJS
        run: npm publish --registry=https://registry.npmjs.org
