name: Build and Publish Angular Library (NPM + GitHub)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build Angular Library
        run: npx ng build commonutilities

      - name: Set Auto Version
        run: |
          cd dist/common-utilities
          npm version 1.0.0-ci.${{ github.run_number }} --no-git-tag-version

      # -----------------------
      # Publish to npmjs
      # -----------------------
      - name: Publish to npmjs
        run: |
          cd dist/common-utilities
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      # -----------------------
      # Publish to GitHub Packages
      # -----------------------
      - name: Publish to GitHub Packages
        run: |
          cd dist/common-utilities
          npm publish --registry=https://npm.pkg.github.com/
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
